---
title: "p8105_hw6_wp2241_lg2973"
author: "Weixin Peng & Lu Gan"
date: "November 14, 2017"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)
library(ggplot2)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(flexdashboard)
```
Cleaning dataset
```{r}
nynoaadat = read_csv("../data/nynoaadat.csv") %>%
  clean_names() %>%
  na.omit 

```
```{r setup, include=FALSE}
library(flexdashboard)
```
Flexdashboard
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
  nynoaadat %>%
  mutate(ymd = date) %>%
  separate(ymd, into = c("year", "month", "day"), sep = "-") %>%
  mutate(
    year = as.factor(year),
    month = as.factor(month),     
    day = as.integer(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin)
         ) %>%
  select(id, year, month, tmax, tmin) %>%
  na.omit %>%
  group_by(month) %>%

plot_ly(y = ~tmax, x = ~month, color = ~month, type = "box",
          colors = "Set2")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nynoaadat %>%
mutate(ymd = date) %>%
separate(ymd, into = c("year", "month", "day"), sep = "-") %>%
mutate(
    year = as.integer(year),
    month = as.integer(month),     
    day = as.integer(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin)
         ) %>%
select(month, tmax, tmin) %>%
na.omit %>%
group_by(month) %>%
mutate(mean_tmax_month = mean(tmax, na.rm = TRUE),
       mean_tmin_month = mean(tmin, na.rm = TRUE)) %>%
plot_ly( x = ~month, y = ~mean_tmax_month, name = 'mean tmax', type = 'scatter', mode = 'lines') %>%
  add_trace(y = ~mean_tmin_month, name = 'mean tmin', mode = 'lines+markers') 
 
```

### Chart C

```{r}

```


